#!/usr/bin/env bash

# Define variables
key_name="school"
bits=4096
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b "${bits}" -C "${key_name}" -N "${passphrase}" -f "${key_name}"

echo "RSA key pair generated successfully."

